name: 'Odyssey momentum deploy action'
description: 'Deploy Odyssey project to their environment'
inputs:
  project:
    description: "The name of the project to deploy."
    required: true
    default: ${{ github.event.repository.name }}
  version:
    description: "The version to deploy."
    required: true
  k8s-credentials:
    description: "Kubernetes credentials (JSON)."
    required: true

runs:
  using: "composite"
  steps:
    - name: "Set K8S creds"
      env:
        K8CRED: ${{ inputs.k8s-credentials }}
      shell: bash
      run: |
        k8s_name=$(echo $K8CRED | jq -r '.cluster_name')
        echo "K8S_NAME=$k8s_name" >> $GITHUB_ENV
        k8s_group=$(echo $K8CRED | jq -r '.cluster_group')
        echo "K8S_GROUP=$k8s_group" >> $GITHUB_ENV
        k8s_creds=$(echo $K8CRED | jq -r '.credential' | tr -d '\n')
        echo "K8S_CREDS=$k8s_creds" >> $GITHUB_ENV
    - uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d  # v1.4.6
      with:
         creds: ${{env.K8S_CREDS}}
    - uses: Azure/aks-set-context@4edaee69f820359371ee8bc85189ac03a21d3a58  # v3.2
      with:
        cluster-name: ${{env.K8S_NAME}}
        resource-group: ${{env.K8S_GROUP}}
    - name: "Rollout"
      shell: bash
      run: |
        kubectl rollout restart deployment "${{ inputs.project }}-deployment"
        kubectl rollout status deployment "${{ inputs.project }}-deployment" --timeout=5m
